name: Deploy to S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --prefix resume-ui-app/resume-ui-app

      - name: Build project
        run: npm run build --prefix resume-ui-app/resume-ui-app
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::913305982102:role/GitHubActionsS3Deployer
          aws-region: us-east-2

      - name: Sync files to S3
        run: |
          aws s3 sync resume-ui-app/resume-ui-app/dist s3://resume-assistant-bucket-arber --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E190EOCBX3X6EN \
            --paths "/*"
