iname: Deploy Frontend

on:
  push:
    branches:
      - main   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v4

     
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      
      - name: Install dependencies
        run: npm ci

      
      - name: Build frontend
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
        run: npm run build

      
      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: resume-assistant-bucket-arber  
          region: us-east-2            
          source-dir: dist
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}:q
          paths: "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
