name: Deploy UI to S3 + CloudFront

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write    # for OIDC
  contents: read

env:
  # Build-time env for Vite
  VITE_API_BASE: ${{ secrets.VITE_API_BASE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: ./resume-ui-app/resume-ui-app
        run: npm ci

      - name: Build (Vite)
        working-directory: ./resume-ui-app/resume-ui-app
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
        run: npm run build

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GHA_AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload static assets with long cache
        run: |
          aws s3 sync ./resume-ui-app/resume-ui-app/dist s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable" \
            --metadata-directive REPLACE

      - name: Upload index.html (short cache)
        run: |
          aws s3 cp ./resume-ui-app/resume-ui-app/dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html" \
            --metadata-directive REPLACE

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

